---
title: "Clases"
subtitle: "Consulta de fuentes y lectura numérica del mundo"
author: "Dra. Daniela Serrano Campos"
date: "`r format(Sys.Date(), '%d de %B de %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    theme: spacelab
    #code_folding: hide
---

<style type="text/css">

/* Navbar Styles */
.navbar {
  background-color: #CD8C95 !important; /* Background color of the navbar */
  border-color: #8B5F65 !important; /* Border color of the navbar */
  background-image: none !important; /* Removes any background image */
  height: 65px; /* Sets navbar height */
}

/* Navbar Link Styles */
.navbar-default .navbar-nav > li > a {
  color: #FFFFFF !important;  /* Text color for links */
  font-weight: bold !important; /* Bold text */
}

.navbar-default .navbar-nav > li > a:hover,
.navbar-default .navbar-nav > li > a:focus {
  color: #8B5F65 !important; /* Hover and focus text color */
  font-weight: bold; /* Keeps text bold on hover/focus */
}

/* Navbar Collapse Menu Styles */
.navbar-collapse {
  background-color: #CD8C95 !important; /* Background color for the collapsed navbar */
}

/* Dropdown Menu Link Styles */
.navbar-nav > li > a {
  color: #FFFFFF; /* Text color for dropdown links */
  font-weight: bold;
  padding: 10px 15px; /* Padding for dropdown links */
}

.navbar-nav > li > a:hover,
.navbar-nav > li > a:focus,
.navbar-nav > .active > a {
  background-color: #005a9c; /* Background color on hover/active */
  color: #FFFFFF; /* Text color on hover/active */
}

/* Active List Group Item Styles */
.list-group-item.active,
.list-group-item.active:focus,
.list-group-item.active:hover {
  z-index: 2;
  color: #8B5F65; /* Text color for active list item */
  background-color: #EEDFCC; /* Background color for active list item */
  border-color: #8B5F65; /* Border color for active list item */
}

/* Title, Subtitle, Author, and Date Styles */
h1.title {
  color: #8B5F65; /* Color for title */
}

h4.subtitle {
  color: #8B5F65; /* Color for subtitle */
}

h5.author {
  color: #8B5F65; /* Color for author */
}

h5.date {
  color: #8B5F65; /* Color for date */
}

/* Hyperlink Styles */
a {
  color:#582C35; /* Text color for hyperlinks */
  text-decoration: none; /* Removes underline from hyperlinks */
}

a:hover {
  color: #005a9c; /* Color when hovering over hyperlinks */
  text-decoration: underline; /* Underlines text when hovering over hyperlinks */
}

a:visited {
  color: #6C4F56; /* Color for visited hyperlinks */
}

a:active {
  color: #4A2C31; /* Color for active hyperlinks (while clicking) */
}

</style>

<div style="color:#8B5F65;">

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
**Nota:** Iré agregando las presentaciones de las clases.


# 1. Clase 1. 8 de agosto. Introducción
[Hacer ejercicio de autoevaluación y subir a classroom](https://uapa.cuaieed.unam.mx/sites/default/files/minisite/static/5955012c-005c-4441-b3a3-e9868a0cf8d1/contenido/index.html) 
<br><br>
<br><br>

## Presentación 1
<iframe src="intro_met_ccss.html" style="width: 800px; height: 600px; border: none;"></iframe>

# 2. Clase 2. 12 de agosto. Introducción
[Hacer ejercicio de autoevaluación y subir a classroom](https://uapa.cuaieed.unam.mx/sites/default/files/minisite/static/5955012c-005c-4441-b3a3-e9868a0cf8d1/contenido/index.html) 
<br><br>
<br><br>

## Presentación 1
<iframe src="Gerring_2014_cap2.html" style="width: 800px; height: 600px; border: none;"></iframe>

## Presentación 2
<iframe src="Gerring_2014_cap3.html" style="width: 800px; height: 600px; border: none;"></iframe>


# 3. Clase 3. 15 de agosto. Fuentes, operadores booleanos y búsqueda 

[Hacer ejercicios de las páginas 1 a la 8 y subir a classroom](https://ri.uaemex.mx/bitstream/handle/20.500.11799/33878/secme-21200.pdf?sequence=1&isAllowed=yhttps://ri.uaemex.mx/bitstream/handle/20.500.11799/33878/secme-21200.pdf?sequence=1&isAllowed=y)

[Ver tutoriales de operadores booleanos, de proximidad, de truncamiento, paréntesis](https://ceib.dgb.unam.mx/index.php/operadores-booleanos)
[Ver tutorial de búsquedas eficientes](https://ceib.dgb.unam.mx/index.php/busquedas-eficientes-de-informacion)


# 4. Clase 4. 19 de agosto. Búsqueda, bitácora y recuperación de información y recursos
[Hacer ejercicio](https://drive.google.com/file/d/1B6-a7QMhrE9L0YQ7MImhAzF81MC7Nue8/view?usp=sharing)


# 5. Clase 5. 22 de agosto. Hacer bases de datos a partir de noticias
[Hacer ejercicio](https://drive.google.com/file/d/11wdnLPLlmIuoPSSd77uU7k5l_WQDx_WA/view?usp=classroom_web&authuser=0)
[Registra tus casos aquí](https://docs.google.com/spreadsheets/d/1pMUBPnanbHVqQlqOswpoHkLisFvxlLy1LVQW0X2XgZQ/edit?usp=classroom_web&authuser=0)

# 6. Clase 6. 26 de agosto. RMarkdown, mendeley, citas
### Introducción a R. Introducción a R y Rstudio. Escritura de comandos en la consola. Cálculos simples. Uso de funciones. Introducción a las variables. Datos numéricos, de caracteres y lógicos. Almacenamiento de múltiples valores como un vector.

[Hacer práctica](https://365inegi-my.sharepoint.com/:f:/g/personal/daniela_serrano_inegi_org_mx/EmnA2xp3FL5CjOyIYtPD1REB2RTvTj4wSwhPB8M_wnD4XA?e=1RQaqZ)

# 7. Clase 7. 29 de agosto. Intro a R
[Hacer práctica](https://365inegi-my.sharepoint.com/:f:/g/personal/daniela_serrano_inegi_org_mx/EpGFWZG3kalGoFjYd7YFhbIBp9ycr4xF_cFBGVEAFaX_LA?e=JALbYc)


# 8. Clase 8. 2 de septiembre 
<iframe src="https://www.bioetica.unam.mx/cursos-autogestivos/multimedia/extra/manuales/cpcfta_manual.pdf" width="100%" height="800px"></iframe>


*Práctica*

1- Tema, pregunta, problema de
investigación


•2.- Algoritmo o ecuación de búsqueda


•3.- Bitácora de búsqueda


•4.- 1 articulo


•5.- Leer resumen e introducción


•6.- Identificar y clasificar las citas
del texto


•7.- Van a hacer 2 citas anotando qué tipo
de cita están haciendo


•8.- Bibliografía




# 10. Clase 10. Citando en RMarkdown
<iframe src="images/portada_rm.pdf" width="100%" height="800px"></iframe>

